server:
   error:
      include-stacktrace: on_param

spring:
   application:
      name: springboot2-essentials
   datasource:
      url: jdbc:mysql://192.168.1.65:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: root
      password: root
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true

   logging: null
   level:
      org:
         hibernate:
            SQL: DEBUG

management: 
   endpoints:
      web:
         exposure:
            include: info, health, metrics, prometheus

info:
   app: Spring Boot 2 Essentials By DevDojo
   website: https://devdojo.academy
   github: https://github.com/devdojobr/sprinngboot2-essentials