version: '3.8'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_DATABASE: devdojo
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo:
